"""
parser.py

Responsible for turning an ESSL "Monthly Status Report (Basic Report)" PDF
into structured employee attendance records.

Design notes
------------
- Never depends on fixed column positions: `utils.split_employee_row` works
  inward from both ends of each line's token list, so it survives minor
  spacing/reflow changes from month to month.
- Primary source of truth is the machine-generated "P" summary column.
  Fallback (recompute from the daily P/A/L/H/HP/WO/WOP/½P status cells) only
  kicks in if the summary can't be read for a row.
- Absent Days/Count are ALWAYS derived from the daily status cells,
  regardless of which attendance source was used.
- One bad row never stops the batch — it's logged and skipped.
"""

from __future__ import annotations

import io
from dataclasses import dataclass, field
from typing import Optional

import pdfplumber

from config import EXPECTED_REPORT_TITLE, NUM_SUMMARY_COLUMNS, SUMMARY_COLUMNS
from logger import logger, timed_step
from utils import (
    ReportMetadata,
    calculate_absent_days,
    calculate_fallback_present,
    extract_metadata,
    format_days_present,
    is_numeric_token,
    split_employee_row,
    to_number,
)

# Lines we can safely ignore outright before even trying to match an
# employee row against them — saves a bit of regex/token work per page.
_SKIP_LINE_PREFIXES = (
    "Generated By",
    "Page No",
    "Monthly Status Report",
    "Days ",
    "Emp. Code:",
    "Emp. Name:",
    "InTime",
    "OutTime",
    "Total",
    "Status ",
)


@dataclass
class EmployeeRecord:
    employee_id: str
    employee_name: str
    days_present: float
    absent_count: int
    absent_days: list[int]
    source: str  # "primary" or "fallback"
    warnings: list[str] = field(default_factory=list)

    def to_output_row(self) -> dict:
        return {
            "Employee ID": self.employee_id,
            "Employee Name": self.employee_name,
            "Days Present": format_days_present(self.days_present),
            "Absent Count": self.absent_count,
            "Absent Days": ",".join(str(d) for d in self.absent_days),
        }


@dataclass
class ParseResult:
    metadata: ReportMetadata
    records: list[EmployeeRecord]
    failed_rows: list[dict]
    primary_count: int = 0
    fallback_count: int = 0

    @property
    def employees_found(self) -> int:
        return len(self.records) + len(self.failed_rows)


def _extract_full_text(pdf_bytes: bytes) -> tuple[str, list[str]]:
    """Return (joined text of all pages, list of per-page text)."""
    pages_text: list[str] = []
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        for page in pdf.pages:
            text = page.extract_text() or ""
            pages_text.append(text)
    return "\n".join(pages_text), pages_text


def _candidate_lines(pages_text: list[str]) -> list[str]:
    lines: list[str] = []
    for page_text in pages_text:
        for line in page_text.split("\n"):
            stripped = line.strip()
            if not stripped:
                continue
            if any(stripped.startswith(p) for p in _SKIP_LINE_PREFIXES):
                continue
            lines.append(stripped)
    return lines


def _parse_row(row: dict, days_in_month: int) -> EmployeeRecord:
    warnings: list[str] = []
    status_tokens = row["status_tokens"]
    summary_tokens = row["summary_tokens"]

    # --- Absent Days: always from daily status cells ---
    absent_count, absent_days = calculate_absent_days(status_tokens)

    # --- Primary: machine-generated summary columns ---
    summary_ok = len(summary_tokens) == NUM_SUMMARY_COLUMNS and all(
        is_numeric_token(t) for t in summary_tokens
    )

    days_present: Optional[float] = None
    source = "fallback"

    if summary_ok:
        summary = dict(zip(SUMMARY_COLUMNS, (to_number(t) for t in summary_tokens)))
        days_present = summary["P"]
        source = "primary"

        # Verification: recompute from daily cells and compare, but the
        # machine summary always wins.
        fallback_present, unmapped = calculate_fallback_present(status_tokens)
        if unmapped:
            warnings.append(f"Unrecognized daily status codes: {unmapped}")
        elif abs(fallback_present - days_present) > 0.01:
            warnings.append(
                f"Verification mismatch for emp {row['employee_code']}: "
                f"machine P={days_present} vs daily-cell calc={fallback_present}. "
                f"Using machine-generated P."
            )
            logger.warning(warnings[-1])

        # Cross-check absent count against the summary's own A column too.
        if abs(summary.get("A", absent_count) - absent_count) > 0.01:
            warnings.append(
                f"Absent count mismatch for emp {row['employee_code']}: "
                f"summary A={summary.get('A')} vs daily-cell count={absent_count}."
            )
            logger.warning(warnings[-1])
    else:
        # --- Fallback: recompute attendance from daily status cells ---
        days_present, unmapped = calculate_fallback_present(status_tokens)
        if unmapped:
            warnings.append(f"Unrecognized daily status codes (fallback): {unmapped}")
        warnings.append(
            f"Summary columns unavailable/unparsable for emp {row['employee_code']}; "
            f"used fallback daily-status calculation."
        )
        logger.warning(warnings[-1])

    return EmployeeRecord(
        employee_id=row["employee_code"],
        employee_name=row["employee_name"],
        days_present=days_present,
        absent_count=absent_count,
        absent_days=absent_days,
        source=source,
        warnings=warnings,
    )


def parse_report(pdf_bytes: bytes, pdf_name: str = "uploaded.pdf") -> ParseResult:
    with timed_step(f"Extract text: {pdf_name}"):
        full_text, pages_text = _extract_full_text(pdf_bytes)

    metadata = extract_metadata(full_text, EXPECTED_REPORT_TITLE)
    if not metadata.days_in_month:
        # Can't safely tokenize rows without knowing how many daily status
        # cells to expect. Surface this clearly rather than guessing.
        raise ValueError(
            "Could not determine the number of days in the report period "
            "(expected a line like 'Jul 01 2026 To Jul 31 2026'). "
            f"Warnings: {metadata.warnings}"
        )

    lines = _candidate_lines(pages_text)

    records: list[EmployeeRecord] = []
    failed_rows: list[dict] = []
    primary_count = 0
    fallback_count = 0

    with timed_step(f"Parse employee rows: {pdf_name}"):
        for line in lines:
            row = split_employee_row(line, metadata.days_in_month)
            if row is None:
                continue
            try:
                record = _parse_row(row, metadata.days_in_month)
            except Exception as exc:  # noqa: BLE001 - never let one row kill the batch
                logger.warning(f"Failed to parse row (skipped): {line!r} — {exc}")
                failed_rows.append({"raw_line": line, "error": str(exc)})
                continue

            if record.source == "primary":
                primary_count += 1
            else:
                fallback_count += 1
            records.append(record)

    if not records:
        logger.warning(f"No attendance records detected in {pdf_name}.")

    return ParseResult(
        metadata=metadata,
        records=records,
        failed_rows=failed_rows,
        primary_count=primary_count,
        fallback_count=fallback_count,
    )
